version: '3.4'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: 'note_redis'
    command: >
      --bind redis
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
    restart: always
    networks:
      - main

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'note_node'
    environment:
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - ORIGIN=${ORIGIN}
    ports:
    - '3006:3000'
    restart: always
    volumes:
      - .:/app
      - /home/tim/Docknote/node_modules:/app/node_modules
    depends_on:
      - redis
    networks:
      - main

  cdn:
    image: nginx
    container_name: 'note_cdn'
    ports:
      - '2006:80'
    volumes:
      - /public:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    networks:
      - main

networks:
  main:
    driver: bridge
