version: '3.4'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: 'note_redis'
    restart: always
    ports:
    - '6380:6379'
    env_file:
      - .env

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'note_node'
    ports:
    - '3006:3000'
    restart: always
    volumes:
      - .:/app
      - /home/tim/Docknote/node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - redis

  cdn:
    image: nginx
    container_name: 'note_cdn'
    ports:
      - '2006:80'
    volumes:
      - /home/tim/Docknote/public:/usr/share/nginx/html
    depends_on:
      - node
