version: '3.4'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: 'note_redis'
    command: >
      --bind note_redis
      --save 60 1
      --loglevel warning
      --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
    - '6380:6379'
    env_file:
      - .env
    volumes:
      - ./data/redis:/data
    networks:
      - docknote_main

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'note_node'
    ports:
    - '3006:3000'
    restart: always
    volumes:
      - .:/app
      - /home/tim/Docknote/node_modules:/app/node_modules
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - docknote_main

  cdn:
    image: nginx
    container_name: 'note_cdn'
    ports:
      - '2006:80'
    volumes:
      - /home/tim/Docknote/public:/usr/share/nginx/html
    depends_on:
      - node

networks:
  docknote_main:
    driver: bridge
