version: '3.4'

services:
  redis:
    image: redis:alpine-latest
    container_name: 'note_redis'
    restart: always
    ports:
    - '6379:6379'
    env_file:
      - .env

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'note_node'
    ports:
    - '3005:3000'
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis