version: '3.4'

services:
  redis:
    image: redis:alpine-latest
    container_name: 'note_redis'
    restart: always
    ports:
    - '6380:6379'
    env_file:
      - .env

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'note_node'
    ports:
    - '3006:3000'
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis

  cdn:
    image: nginx
    container_name: 'autorin_cdn'
    ports:
      - '2006:80'
    volumes:
      - /home/tim/daniela-arnold/backend/main:/usr/share/nginx/html
    depends_on:
      - frontend
